### ISSUE TITLE
Error messages should be human-friendly

### ISSUE THREAD

**Issue by macabeus** [vendure-ecommerce/deity-falcon-vendure-api#6]
I noticed that when an error happens, the error messages display `GraphQL error: ...`. But I think that we should cut this part, to be more human-friendly.

![image](https://user-images.githubusercontent.com/9501115/94028331-b7a15b80-fdb3-11ea-88c2-2ca403592544.png)

And if we haven't an human-friendly message, just show something like "Unknown error. Please try again later", instead of:

![image](https://user-images.githubusercontent.com/9501115/94027991-5da09600-fdb3-11ea-89bc-a6f543c7d511.png)

**Comment by michaelbromley** [comment]
I'm closing this and archiving this repo because Deity just announced that Falcon will no longer be open source. In Slack messages dated 4th Nov 2020, it was announced:

> Falcon Open Source will no longer be available openly, but only in private repositories. 
> Q: will the npm packages still be openly available?
> they won't be openly available but if you need access we can give it to you and your team.

Therefore it is no longer feasible to maintain an adapter for what is now a closed-source project, where setting up a dev environment is not easy.
